---
title: "Exploratory Analysis of North Carolina Traffic Stop Data"
author: ''
date: '2021-02-17'
slug: exploratory-analysis-of-north-carolina-traffic-stop-data
categories:
- eda
- traffic stops
- Highcharts
- data visualization
tags: []
subtitle: Visualizing traffic stops in North Carolina
summary: ''
authors: []
lastmod: '2021-02-17T19:08:49-05:00'
featured: no
image:
  caption: <span>Photo by <a href="https://unsplash.com/@introspectivedsgn?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Erik
    Mclean</a> on <a href="https://unsplash.com/s/photos/police-car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>
  focal_point: ''
  preview_only: no
projects: []
links:
- icon: github
  icon_pack: fab
  name: Github
  url: https://github.com/shanejorr/shanes-site/blob/main/content/post/2021-02-17-exploratory-analysis-of-north-carolina-traffic-stop-data/index.en.Rmd
draft: yes
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F,
                      error = F)
```

```{r importLibraries}
library(glue)
library(gt)
library(vroom)
library(tidycensus)
library(lubridate)
library(highcharter)
library(scales)
library(leaflet)
library(tigris)
library(widgetframe)
library(tidyverse)
```

```{r}
# create ggplot theme for this post
post_theme <- theme_minimal() +
  theme(legend.position = 'bottom',
        plot.title = element_text(size = 11),
        plot.subtitle = element_text(size = 10),
        axis.title = element_text(size = 10))

theme_set(post_theme)
```

```{r importData, cache = T}
nc_stops <- vroom('/home/shane/Documents/nc_statewide_2020_04_01.csv.zip',
                  col_select = -contains('raw'))

# get 2009 - 2013 5 year and aggregate
pop_years <- seq(2009, 2013, 1)

n_years <- length(pop_years)

nc_stops <- nc_stops %>%
  filter(str_detect(reason_for_stop, "^Speed")) %>%
  mutate(year = year(date)) %>%
  # only keep between years 2009 and 2013 
  # 2013 is final full year of stop data
  filter(year %in% !!pop_years)
```

```{r}
nc_stops <- nc_stops %>%
  # remove string so that it matches with census data
  mutate(county_name = str_remove_all(county_name, ' County'),
         # rename misspelled county name
         county_name = str_replace_all(county_name, 'Tyrell', 'Tyrrell'))
```

```{r}
# census and shapefile information ----------------

# recode integers fo dates to years
recode_date <- c(
  `3` = 2010,
  `4` = 2011,
  `5` = 2012,
  `6` = 2013,
  `7` = 2014,
  `8` = 2015
)

# import population data by county and race
county_pop <- get_estimates(geography = "county", state = 'NC',
                            product = 'population', 
                            time_series = T,
                            year = 2018) %>%
  # remove string so that it matches with census data
  # only keep 2010 - 2014
  filter(DATE %in% seq(3, 6)) %>%
  # remove string so that it matches with traffic stop data
  mutate(NAME = str_remove_all(NAME, ' County, North Carolina')) %>%
  # make density and population different columns
  pivot_wider(id_cols = c('NAME', 'DATE', 'GEOID'),
              names_from = 'variable', values_from = 'value') %>%
  # aggregate 2010 - 2014 so it can be merged with aggregated stop data
  # sum population so we can divide by total stops between 2010-2014
  group_by(NAME, GEOID) %>%
  summarize(POP = sum(POP),
            DENSITY = mean(DENSITY))

```

```{r}
# per capita number of stops ----------------

# calculate number of stops overall by year
per_capita_stops <- nc_stops %>%
  filter(!is.na(county_name)) %>%
  group_by(county_name) %>%
  count() %>%
  arrange(county_name) %>%
  left_join(county_pop, 
            by = c('county_name' = 'NAME')) %>%
  # calculate stops per 100 people
  mutate(stops_per = n/(POP/100)) %>%
  # round stops in new column for tooltip
  mutate(stops_tooltip = round(stops_per, 1)) %>%
  # create additional data points for tooltip
  mutate(year_pop = number((POP/!!n_years), accuracy = 1, big.mark = ','),
         year_stops = number((n/!!n_years), accuracy = 1, big.mark = ','))
```

## Counties with the most stops per 100 residents

```{r fig.width = 5, fig.height = 14}
# title and tooltip for stops per 100 plots
stops_per_title <-   "North Carolina County Speeding Stops Per 100 Residents: 2009 - 2013"

stops_per_tooltip <- "<b>{point.county_name}</b><br>
                      Stops per 100 residents: <b>{point.stops_tooltip}</b><br>
                      Population: <b>{point.year_pop}</b><br>
                      Stops per year: <b>{point.year_stops}</b>"

h_couty_bar <- per_capita_stops %>%
  arrange(desc(stops_per)) %>%
  hchart(., "bar", hcaes(x = county_name, y = stops_per)) %>%
    hc_xAxis(labels = list(enabled = FALSE),
             title = list(text = 'North Carolina counties')) %>%
    hc_yAxis(title = list(text = "Stops per 100 residents")) %>%
    hc_tooltip(
      headerFormat = "",
      pointFormat = stops_per_tooltip
    ) %>%
  hc_title(text = stops_per_title) %>% 
  hc_subtitle(text = "Hover over bars to see county name")

frameWidget(h_couty_bar, height = 400, width = '95%')
```

### Map of stops per 100 residents

```{r}
# chloropath map of speeding stops per 100 residents by NC county
h_county_cloro <- hcmap(
  "countries/us/us-nc-all",
  data = per_capita_stops,
  value = "stops_per",
  joinBy = c("fips", "GEOID"),
  dataLabels = list(enabled = FALSE),
  borderColor = "#FAFAFA",
  borderWidth = 0.1,
  tooltip = list(
      headerFormat = "",
      pointFormat = stops_per_tooltip
    )
  ) %>%
  hc_title(text = stops_per_title) %>% 
  hc_subtitle(text = "Hover over county to see county name and rate")

frameWidget(h_county_cloro, height = 400, width = '95%')
```

## Relationship between county population density and number of stops

```{r}
h_county_scatter <- per_capita_stops %>%
  mutate(density_tooltip = round(DENSITY, 0)) %>%
  hchart(., "scatter", hcaes(x = DENSITY, y = stops_per)) %>%
    hc_xAxis(type = 'logarithmic') %>%
    hc_tooltip(
        headerFormat = "",
        pointFormat = "<b>{point.county_name}</b>
                      <br># of Stops: <b>{point.n}</b>
                      <br>Density: <b>{point.density_tooltip}</b>"
      ) %>%
    hc_title(text = "Relationship between county population density and per capita speeding stops") %>% 
    hc_subtitle(text = "Each dot is a North Carolina county | Data reflects 2009 - 2013") %>%
    hc_xAxis(title = list(text = 'County population density')) %>%
    hc_yAxis(title = list(text = "Number of speeding stops per 100 residents")) 

frameWidget(h_county_scatter, height = 300, width = '95%')
```

## Days with the highest number of stops

```{r}
# create dataset of daily aggregate number of of stops for all NC

daily_stops <- nc_stops %>%
  filter(year == max(year)) %>%
  # get daily totals for each interstate group
  drop_na(date) %>%
  count(date) %>%
  # calculate percentage of total number of stops
  ungroup() %>%
  mutate(total_stops = sum(n),
         perc_total = n / total_stops) %>%
  arrange(date)

# create abbreviated month and day for tooltip
daily_stops$date_tooltip <- glue("{month.abb[month(daily_stops$date)]} {day(daily_stops$date)}, {year(daily_stops$date)}")
```

```{r}
# line plot of daily stops
h_county_daily <- hchart(daily_stops, 'line', hcaes(x = date, y = n)) %>% 
  hc_xAxis(type = "datetime") %>%
  hc_tooltip(
    headerFormat = "",
    pointFormat = "<b>{point.date_tooltip}</b>
                      <br>Number of stops: <b>{point.n}</b>"
  ) %>%
  hc_title(text = 'Number Of Speeding Stops Per Day in North Carolina - 2013') %>% 
  hc_yAxis(title = list(text = '# of stops')) %>%
  hc_xAxis(title = list(text = NULL)) %>%
  # add lines and bands for dates
  hc_xAxis(
    plotLines = list(
      list(label = list(text = "July 4th"), color = "#7F7F7F", width = 2, zIndex = 1,
           value = datetime_to_timestamp(as.Date('2013-07-04')), dashStyle = 'Dash'),
      list(label = list(text = "Christmas"), color = "#7F7F7F", width = 2, zIndex = 2,
           value = datetime_to_timestamp(as.Date('2013-12-25')), dashStyle = 'Dash'),
      list(label = list(text = "Labor Day"), color = "#7F7F7F", width = 2, zIndex = 3,
           value = datetime_to_timestamp(as.Date('2013-09-02')), dashStyle = 'Dash'),
      list(label = list(text = "Thanksgiving"), color = "#7F7F7F", width = 2, zIndex = 4,
           value = datetime_to_timestamp(as.Date('2013-11-28')), dashStyle = 'Dash'),
      list(label = list(text = "Memorial Day"), color = "#7F7F7F", width = 2, zIndex = 5,
           value = datetime_to_timestamp(as.Date('2013-05-27')), dashStyle = 'Dash')
    )
  )

frameWidget(h_county_daily, height = 300, width = '95%')
```

## Stops by department

```{r}
# create city-level stop and population dataset

# get city populations

place_pop <- map_df(pop_years, function(yr) {
    get_acs(year = yr,
            survey = "acs5", 
            geography = "place", state = "NC", 
            variables = "B01003_001") %>%
    mutate(year = !!yr)
}) %>%
  # only keep cities with five years of population data
  group_by(GEOID) %>%
  mutate(n = n()) %>%
  filter(n == !!n_years) %>%
  # sum all five years of populations
  # we can do this because traffic stops will be summed for the entire five years
  group_by(GEOID, NAME) %>%
  summarize(pop = sum(estimate)) %>%
  # only keep towns with at least 7,500 people
  ungroup() %>%
  filter((pop/!!n_years) > 5000) %>%
  # clean up city names so they match traffic stop names
  mutate(NAME = str_remove_all(NAME, ", North Carolina"),
         NAME = str_remove_all(NAME, " town| city| CDP| village"),
         NAME = str_replace_all(NAME, "Charlotte", "Charlotte-Mecklenburg"))

# get department data
dept_stops <- nc_stops %>%
  # only keep local police departments
  filter(!is.na(department_name),
         str_detect(department_name, 'Police Dep')) %>%
  filter(!str_detect(department_name, 'College|University'),
         !str_detect(department_name, '^NC|^UNC'),
         !str_detect(department_name, 'Hospital')) %>%
  # clean up department names to match population dataset
  mutate(department_name = str_remove_all(department_name, " Police Department"),
         department_name = str_trim(department_name)) %>%
  # aggregate number of stops by department
  group_by(department_name) %>%
  count() %>%  
  # merge in population data
  left_join(place_pop, by = c('department_name' = 'NAME')) %>%
  # only keep departments where we have popualtion data
  drop_na(pop) %>%
  mutate(year_pop = number((pop/!!n_years), accuracy = 1, big.mark = ','),
         year_stops = number((n/!!n_years), accuracy = 1, big.mark = ','),
         stops_per = n/(pop/100),
         stops_per_tooltip = round(stops_per, 1))
```

```{r fig.width = 5, fig.height = 14}
# plot stops per 100 for each city

# title and tooltip for stops per 100 plots
stops_per_title <-   "North Carolina City Speeding Stops Per 100 Residents: 2009 - 2013"
stops_per_tooltip <- "<b>{point.department_name}</b><br>
                      Stops per 100 residents: <b>{point.stops_per_tooltip}</b><br>
                      Population: <b>{point.year_pop}</b><br>
                      Stops per year: <b>{point.year_stops}</b>"

h_city_bar <- dept_stops %>%
  arrange(desc(stops_per)) %>%
  hchart(., "bar", hcaes(x = department_name, y = stops_per)) %>%
    hc_xAxis(labels = list(enabled = FALSE),
             title = list(text = 'North Carolina cities')) %>%
    hc_yAxis(title = list(text = "Stops per 100 residents")) %>%
    hc_tooltip(
      headerFormat = "",
      pointFormat = stops_per_tooltip
    ) %>%
  hc_title(text = stops_per_title) %>% 
  hc_subtitle(text = "Hover over bars to see city name")

frameWidget(h_city_bar, height = 450, width = '95%')
```


```{r}
# get place data
nc_places <- places("North Carolina", progress_bar = FALSE) %>%
  # only keep places that are in the stop dataset
  filter(GEOID %in% !!dept_stops$GEOID)

# merge place data with stop dataset
dept_stops_geo <- dept_stops %>%
  left_join(nc_places, by = 'GEOID') %>%
    mutate(across(starts_with("INTPT"), ~as.numeric(.)))
```

```{r}
# create leaflet map of places

# popup label
city_labels <- labs <- lapply(seq(nrow(dept_stops_geo)), function(i) {
  paste0( '<b>', dept_stops_geo[i, "department_name"], '</b><br>', 
          'Stops per 100 residents: <b>',  dept_stops_geo[i, "stops_per_tooltip"], '</b><br>',
          'Population: <b>', dept_stops_geo[i, "year_pop"], '</b><br>',
          'Stops per year: : <b>', dept_stops_geo[i, "year_stops"], '</b>') 
})

l <- dept_stops_geo %>%
  rename(lng = INTPTLON, lat = INTPTLAT) %>%
  leaflet() %>% 
  setView(lng = -79.0193, lat = 35.7596, zoom = 7) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(
   radius = ~stops_per,
   label = lapply(city_labels, htmltools::HTML),
   stroke = FALSE, fillOpacity = 0.3
  )

frameWidget(l, height = '400')
```